### ISSUE TITLE
PackageNotFound

### ISSUE THREAD

**Issue by adityog** [conda-forge/pysoundfile-feedstock#2] opened 2018-06-05 11:29 UTC
I am trying to install pysoundfile using Anaconda Prompt
Performed the following steps : 
>conda config --add channels conda-forge
>conda install pysoundfile
I got a _PackagesNotFoundError_
Similar error showed up when I tried using >conda install -c conda-forge pysoundfile

Can someone help out?

**Comment by ocefpaf** [comment] 2018-06-05 11:38
`pysoundfile` should not be `noarch` b/c it depends on `libsndfile` and that is absent on Windows :-/

See https://github.com/conda-forge/pysoundfile-feedstock/blob/master/recipe/meta.yaml#L29

PS: I'm guessing you are on Windows, if so we can close this.

**Comment by scopatz** [comment] 2018-06-05 12:10
This package is noarch though. If the dependencies exist on a platform, then it would work without modification.  

It would be great to get libsndfile working on windows.

**Comment by ocefpaf** [comment] 2018-06-05 12:43
Well... It is some "arch" b/c we would need to use a pre-selector there `# [not win]`. Anyway, I'm OK keeping the `noarch` here b/c conda's error is OK IMO there. The problem is that people searching for on Windows it will have the impression that it is installable when it is not.

**Comment by endolith** [comment] 2018-12-01 07:06
I had the impression this is installable but it's not :(

**Comment by tjwilli58** [comment] 2018-12-01 23:27
IMO, it's a little misleading that conda search can find the package, but not be able to install it.

> (base) C:\Users\Tim>conda search pysoundfile
> Loading channels: done
> \# Name Version Build Channel
> pysoundfile 0.9.0.post1 py_0 conda-forge
> pysoundfile 0.10.1 py_0 conda-forge
> 
> (base) C:\Users\Tim>conda install pysoundfile
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> pysoundfile
> Current channels:
> 
> https://conda.anaconda.org/conda-forge/win-64
> https://conda.anaconda.org/conda-forge/noarch
> https://repo.anaconda.com/pkgs/main/win-64
> https://repo.anaconda.com/pkgs/main/noarch
> https://repo.anaconda.com/pkgs/free/win-64
> https://repo.anaconda.com/pkgs/free/noarch
> https://repo.anaconda.com/pkgs/r/win-64
> https://repo.anaconda.com/pkgs/r/noarch
> https://repo.anaconda.com/pkgs/pro/win-64
> https://repo.anaconda.com/pkgs/pro/noarch
> https://repo.anaconda.com/pkgs/msys2/win-64
> https://repo.anaconda.com/pkgs/msys2/noarch
> To search for alternate channels that may provide the conda package you’re
> looking for, navigate to
> 
> https://anaconda.org
> and use the search bar at the top of the page.

**Comment by endolith** [comment] 2018-12-02 01:06
It would be best if it were installable :D  `pip install soundfile` installs the binaries.  Couldn't conda do that, too?

**Comment by scopatz** [comment] 2018-12-03 00:15
@endolith - which binaries do you think this should install?

**Comment by tjwilli58** [comment] 2018-12-03 00:42
The binaries that are installed when you do a `pip install soundfile`.

**Comment by scopatz** [comment] 2018-12-03 00:48
@tjwilli58 - which ones, exactly?

**Comment by tjwilli58** [comment] 2018-12-03 00:58
`libsndfile64bit.dll`

Isn't the issue that libsndfile is not on Windows? When you install it from `pip`, the DLL is put in `site-packages`. I don't really understand all that goes in to making a conda package. I did look at the conda docs this past summer on creating a package with [conda skeletion](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html#building-a-simple-package-with-conda-skeleton-pypi), and it seems that this is what's being done, but I don't understand how to get the recipe to just do a `pip install` on a Windows architecture.

> (base) C:\Users\Tim\Anaconda3\Lib\site-packages>dir /s _soundfile_data
>  Volume in drive C is Acer
>  Volume Serial Number is 1C3B-1723
> 
>  Directory of C:\Users\Tim\Anaconda3\Lib\site-packages\_soundfile_data
> 
> 12/02/2018  07:41 PM    <DIR>          .
> 12/02/2018  07:41 PM    <DIR>          ..
> 12/02/2018  07:41 PM            26,518 COPYING
> 12/02/2018  07:41 PM         1,710,592 libsndfile64bit.dll
>                2 File(s)      1,737,110 bytes
> 
>      Total Files Listed:
>                2 File(s)      1,737,110 bytes
>                2 Dir(s)  138,278,154,240 bytes free
>

**Comment by tjwilli58** [comment] 2018-12-03 01:09
There is a [libsndfile](https://github.com/conda-forge/libsndfile-feedstock) package on conda-forge, but of course, there have been problems getting a [windows build](https://github.com/conda-forge/libsndfile-feedstock/issues/4).

**Comment by tjwilli58** [comment] 2018-12-03 01:12
I should have linked to the [PR](https://github.com/conda-forge/libsndfile-feedstock/pull/7) for the libsndfile build.

**Comment by scopatz** [comment] 2018-12-03 17:02
I believe the real fix is to libsndfile so please pursue that PR. Thanks!

**Comment by scopatz** [comment] 2018-12-27 15:35
please feel free to reopen if neede.

**Closed as completed by scopatz** 2018-12-27 15:35 UTC

**Comment by tjwilli58** [comment] 2018-12-27 15:39
@scopatz , thanks for closing this for me. I forgot about it.

**Comment by scopatz** [comment] 2018-12-27 15:41
No problem!

**Comment by endolith** [comment] 2018-12-27 16:51
Is it not possible to install binaries the same way `pip install pysoundfile` does it?

**Comment by scopatz** [comment] 2018-12-27 16:54
@endolith - no, it is not safe to do that because they are likely compiled with a different set of compilers that may not be binary compatible with the other libraries in conda-forge.  To guarantee compatibility, we need to build binaries for each system.
